# Generated by Django 3.0.2 on 2020-01-26 19:52

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='World',
            new_name='Word',
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='world',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='world_text',
            new_name='word_text',
        ),
    ]
