# Generated by Django 3.0.2 on 2020-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='example',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='definition',
            name='phonetic',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='word',
            name='word_class',
            field=models.CharField(default='', max_length=200),
        ),
    ]
