# Generated by Django 3.0.2 on 2020-02-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_extends_word_and_defintion_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='example',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='definition',
            name='phonetic',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
